services:
  spark-master:
    container_name: spark-master-alpine
    build: 
      dockerfile: ./SparkAlpine.Dockerfile
    image: spark-image-alpine
    entrypoint: [ './entrypoint.sh', 'master' ]
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080" ]
      interval: 5s
      timeout: 3s
      retries: 3
    volumes:
      - ../data:/opt/spark/data
      - ../spark-apps:/opt/spark/apps
      - ../spark-logs:/opt/spark/spark-events
    env_file:
      - .env.spark
    ports:
      - '9090:8080'
      - '7077:7077'

  spark-history-server:
    container_name: spark-history-alpine
    image: spark-image-alpine
    entrypoint: [ './entrypoint.sh', 'history' ]
    depends_on:
      - spark-master
    env_file:
      - .env.spark
    volumes:
      - ../spark-logs:/opt/spark/spark-events
    ports:
      - '18080:18080'

  spark-worker:
    image: spark-image-alpine
    entrypoint: [ './entrypoint.sh', 'worker' ]
    depends_on:
      - spark-master
    env_file:
      - .env.spark
    volumes:
      - ../data:/opt/spark/data
      - ../spark-apps:/opt/spark/apps
      - ../spark-logs:/opt/spark/spark-events

volumes:
  data:
    external: true
  spark-apps:
    external: true
  spark-logs:
    external: true